name: CI

on: [push]

jobs:
  build_frontend:
    name: Build frontend image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build docker image
        run: docker image build -t gulag -f Dockerfile .

      - name: Push to Docker hub if stage
        if: github.ref == 'refs/heads/stage'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag gulag dhcenter/gulag:stage
          docker push dhcenter/gulag:stage
          docker logout
      - name: Push to Docker hub if prod
        if: github.ref == 'refs/heads/prod'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag gulag dhcenter/gulag:prod
          docker push dhcenter/gulag:prod
          docker logout
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy stage
        if: github.ref == 'refs/heads/stage'
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: cd ~/gulag/stage/ && ./deploy.sh
          host: ${{ secrets.SERVER_HOST }}
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy prod
        if: github.ref == 'refs/heads/prod'
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: cd ~/gulag/prod/ && ./deploy.sh
          host: ${{ secrets.SERVER_HOST }}
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY }}
